apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #creationTimestamp: "2025-02-06T07:28:34Z"
  #generation: 10
  name: appofapps-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    #- resources-finalizer.argocd.argoproj.io/background
  #resourceVersion: "60252"
  #uid: 4516aaf4-bace-40d5-8cf6-d9974c7c7b08
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: my-study
  source: #[]
    path: apps
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD 
  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions: []
    #- PrunePropagationPolicy=background # Supported policies are background, foreground and orphan. 